default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 20
  username: root
  password: root

development:
  <<: *default
  database: shine_development

production:
  <<: *default
  database: shine_production
